// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHL4RGTwzf9q0BdaGuxmJde-LUkZtyRy0',
    appId: '1:531503348047:web:93a072b38f0c861801ad3a',
    messagingSenderId: '531503348047',
    projectId: 'accentdetectionapp-182e1',
    authDomain: 'accentdetectionapp-182e1.firebaseapp.com',
    storageBucket: 'accentdetectionapp-182e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArnSGYWEZAIkfJe58STs3y2K9aS7V4Gng',
    appId: '1:531503348047:android:caf64842d78f400801ad3a',
    messagingSenderId: '531503348047',
    projectId: 'accentdetectionapp-182e1',
    storageBucket: 'accentdetectionapp-182e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkILyqIkKaZ8crEVBcWqP3meuFb6bPsxI',
    appId: '1:531503348047:ios:c5811abf44ba7b4401ad3a',
    messagingSenderId: '531503348047',
    projectId: 'accentdetectionapp-182e1',
    storageBucket: 'accentdetectionapp-182e1.appspot.com',
    iosBundleId: 'com.example.accentDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkILyqIkKaZ8crEVBcWqP3meuFb6bPsxI',
    appId: '1:531503348047:ios:c5811abf44ba7b4401ad3a',
    messagingSenderId: '531503348047',
    projectId: 'accentdetectionapp-182e1',
    storageBucket: 'accentdetectionapp-182e1.appspot.com',
    iosBundleId: 'com.example.accentDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHL4RGTwzf9q0BdaGuxmJde-LUkZtyRy0',
    appId: '1:531503348047:web:25a89edb2efe849b01ad3a',
    messagingSenderId: '531503348047',
    projectId: 'accentdetectionapp-182e1',
    authDomain: 'accentdetectionapp-182e1.firebaseapp.com',
    storageBucket: 'accentdetectionapp-182e1.appspot.com',
  );

}